let posts = [
    {
        imgSrc: 'img/Approach.jpg',
        title: 'Blog Post Title 1',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-about.jpg',
        title: 'Blog Post Title 2',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-consult.jpg',
        title: 'Blog Post Title 3',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/Approach.jpg',
        title: 'Blog Post Title 1',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-about.jpg',
        title: 'Blog Post Title 2',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-consult.jpg',
        title: 'Blog Post Title 3',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/Approach.jpg',
        title: 'Blog Post Title 1',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-about.jpg',
        title: 'Blog Post Title 2',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    },
    {
        imgSrc: 'img/bg-consult.jpg',
        title: 'Blog Post Title 3',
        excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
        content: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis, urna eget aliquam feugiat, lacus risus...'
        ]
    }
];

function loadPosts() {
    const blogPostsContainer = document.getElementById('blog-posts');
    posts.forEach((post, index) => {
        const postElement = document.createElement('div');
        postElement.classList.add('post');
        postElement.innerHTML = `
            <img src="${post.imgSrc}" alt="Blog Post ${index + 1}">
            <h3 class="post-title">${post.title}</h3>
            <p class="post-excerpt">${post.excerpt}</p>
            <a href="fullpost.html?post=${index}" class="read-more">Read More</a>
        `;
        blogPostsContainer.appendChild(postElement);
    });
}

function getQueryParam(name) {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get(name);
}

function loadFullPost() {
    const postIndex = getQueryParam('post');
    if (postIndex !== null) {
        const post = posts[parseInt(postIndex)];
        if (post) {
            document.getElementById('full-post-title').textContent = post.title;
            document.getElementById('full-post-image').src = post.imgSrc;
            document.getElementById('full-post-part1').textContent = post.content[0];
            document.getElementById('full-post-part2').textContent = post.content[1];
            document.getElementById('full-post-part3').textContent = post.content[2];
        }
    }
}

function goBack() {
    window.location.href = 'blog.html';
}

document.addEventListener('DOMContentLoaded', function() {
    if (document.getElementById('blog-posts')) {
        loadPosts();
    } else if (document.getElementById('full-post')) {
        loadFullPost();
    }
});